name: Fix zip filename
description: Renames config.json to secrets.json in zip
runs:
  using: composite
  steps:
    - name: Fix filename
      run: |
        python3 ./.github/actions/fix-zip/fix_zip.py
