name: Fetch Encrypted Secrets

on:
  workflow_call:
    inputs:
      zip_url:
        required: true
        type: string

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Download encrypted zip from URL
        run: |
          curl -L -o secrets.zip "${{ inputs.zip_url }}"
          echo "Downloaded secrets.zip"

      - name: Fix filename for decrypt action
        uses: ./.github/actions/fix-zip

      - name: Upload Encrypted Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-zip
          path: secrets.zip
          retention-days: 1
