name: Fetch Encrypted Secrets

on:
  workflow_call:
    inputs:
      zip_url_base:
        required: true
        type: string
      zip_filename:
        required: true
        type: string

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download encrypted zip from rdgen server
        run: |
          FULL_URL="${{ inputs.zip_url_base }}/get_zip?filename=${{ inputs.zip_filename }}"
          echo "Downloading from: $FULL_URL"
          curl -L -o secrets.zip "$FULL_URL"
          echo "Downloaded secrets.zip"

      - name: Fix filename for decrypt action
        uses: ./.github/actions/fix-zip

      - name: Upload Encrypted Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-zip
          path: secrets.zip
          retention-days: 1
