name: Fetch Encrypted Secrets

on:
  workflow_call:
    inputs:
      config_json:
        required: true
        type: string

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Create zip from config
        run: |
          echo '${{ inputs.config_json }}' > config.json
          zip -P VLliY40K5wycvQkK secrets.zip config.json
          rm config.json

      - name: Upload Encrypted Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-zip
          path: secrets.zip
          retention-days: 1
